export default {
    PIN_DISPLAY_E: 13,
    PIN_DISPLAY_RS: 12,
    PIN_DISPLAY_DATA1: 16,
    PIN_DISPLAY_DATA2: 19,
    PIN_DISPLAY_DATA3: 20,
    PIN_DISPLAY_DATA4: 26,
    PIN_BUTTON_FILTER: 25,
    PIN_BUTTON_PUMP: 8,
    PIN_RELAIS_FILTER: 9,
    PIN_RELAIS_PUMP: 11
}