export default {
    PIN_DISPLAY_E: 21,
    PIN_DISPLAY_RS: 20,
    PIN_DISPLAY_DATA1: 19,
    PIN_DISPLAY_DATA2: 13,
    PIN_DISPLAY_DATA3: 6,
    PIN_DISPLAY_DATA4: 5,
    PIN_DISPLAY_LIGHT:26,
    PIN_BUTTON_SALT: 9,
    PIN_BUTTON_PUMP: 10,
    PIN_BUTTON_LIGHT: 11,
    PIN_RELAIS_SALT: 14,
    PIN_RELAIS_PUMP: 15
}